import traci
import time
import sys
import os
import xml.etree.ElementTree as ET
import pandas as pd

from ElectricVehicles import ElectricVehicles
from evse_class import EVSE_class, EnergyPool
from grid_controller import GridController
from power_grid_manager import PowerGridManager
from ChargingProcess import *

# ----------------------------------------------------
# CONFIGURATION
# ----------------------------------------------------

# Accept scenario directory as command line argument
SCENARIO_DIR = sys.argv[1] if len(sys.argv) > 1 else "../data/scenarios/default"
SUMO_CONFIG = os.path.join(SCENARIO_DIR, "sim.sumocfg")

# Load UI-provided simulation parameters (written by biflex_local_runner)
import json as _json_params
_sim_params_file = os.path.join(SCENARIO_DIR, "sim_params.json")
_sim_params = {}
if os.path.exists(_sim_params_file):
    with open(_sim_params_file, 'r') as _f:
        _sim_params = _json_params.load(_f)
    print(f"[CONFIG] Loaded UI simulation parameters from sim_params.json")

TRACKING_INTERVAL = 1                     # 1 sec timestep
RAMPUP_DURATION = int(_sim_params.get('rampup_duration', 20))            # seconds (ramp up)
MAX_CHARGING_POWER_KW = int(_sim_params.get('max_charging_power_kw', 200))  # kW (server default)
POSITION_TOLERANCE = 1.0
SOC_CHANGE_THRESHOLD = float(_sim_params.get('soc_change_threshold', 0.05))  # detect charging

# EV type detection: Match base type and unique types for wallbox owners
# Pattern: "veh_ev" or "veh_ev_personXXX"
def is_ev_type(vehicle_type):
    """Check if vehicle type is an EV (base or unique wallbox owner type)."""
    return vehicle_type.startswith("veh_ev")

# Global energy pool configuration (fallback if no grid model available)
MAX_TOTAL_GRID_POWER_KW = 500             # Total available power from grid/source
USE_GRID_CONTROLLER = True                # Use realistic grid model instead of simple EnergyPool

# Read dynamic grid config if available (generated by biflex_local_runner based on map area)
import json as _json_cfg
_grid_config_file = os.path.join(SCENARIO_DIR, "grid_config.json")
if os.path.exists(_grid_config_file):
    with open(_grid_config_file, 'r') as _f:
        _grid_cfg = _json_cfg.load(_f)
    MAX_TOTAL_GRID_POWER_KW = _grid_cfg.get("max_grid_power_kw", MAX_TOTAL_GRID_POWER_KW)
    print(f"[CONFIG] Dynamic grid power: {MAX_TOTAL_GRID_POWER_KW:.0f} kW (from grid_config.json, area={_grid_cfg.get('area_km2', '?')} km2)")
else:
    print(f"[CONFIG] Using default grid power: {MAX_TOTAL_GRID_POWER_KW} kW (no grid_config.json)")

# Home charging station configuration
HOME_CHARGING_PERCENTAGE = float(_sim_params.get('home_charging_percentage', 0.05))  # % of EVs have home charging
V2G_SOC_THRESHOLD = float(_sim_params.get('v2g_soc_threshold', 0.50))               # Discharge if SOC > threshold
V2G_DISCHARGE_POWER_KW = int(_sim_params.get('v2g_discharge_power_kw', 50))         # Max discharge power per vehicle
GRID_CAPACITY_WARNING_THRESHOLD = float(_sim_params.get('grid_capacity_warning_threshold', 0.90))  # Trigger V2G threshold

# Create logs directory in scenario folder
LOGS_DIR = os.path.join(SCENARIO_DIR, "traci_logs")
os.makedirs(LOGS_DIR, exist_ok=True)

OUTPUT_CHARGING_LOG = os.path.join(LOGS_DIR, "model_log_data.csv")
OUTPUT_EVSE_LOG = os.path.join(LOGS_DIR, "evse_log_data.csv")

# apply setChargingPower before advancing the simulation step
APPLY_POWER_BEFORE_STEP = True

# how often to flush evse_log to disk during run (0 = only at the end)
EVSE_LOG_FLUSH_INTERVAL = 1000

# Energy tracking: detect when a charging session ends and log cumulative energy
TRACK_CHARGING_SESSIONS = True

# ----------------------------------------------------
# INTERNAL STATE
# ----------------------------------------------------

# Global energy pool instance (will be replaced with GridController if available)
energy_pool = None
grid_controller = None

ev_objects = {}                 # veh_id -> ElectricVehicles()
evse_objects = {}               # station_id -> EVSE_class()
home_stations = {}              # veh_id -> station_id (for vehicles with home charging)
home_station_positions = {}     # station_id -> (x, y) position of home station
vehicle_home_positions = {}     # veh_id -> (x, y) home position
charging_start_time = {}        # veh_id -> timestamp when charging started
charging_status = {}            # veh_id -> (is_charging, station)
last_soc = {}
charging_session_energy = {}    # veh_id -> accumulated energy in kWh during current session
session_start_soc = {}          # veh_id -> SOC at the start of current charging session
v2g_session_energy = {}         # veh_id -> accumulated energy in kWh during V2G session
home_session_tracker = {}       # veh_id -> {start_time, start_soc, charge_kwh, v2g_kwh, station_id}
peak_grid_usage_kw = 0          # Track peak grid usage across entire simulation
SUMO_STEP_LENGTH = 10           # seconds - must match step-length in sim.sumocfg

charging_stations_cache = {}    # lane_id -> [(cs_id, start, end)]
home_charging_cache = {}        # station_id -> (x, y, tolerance) for home stations
wallbox_map = {}                # owner_id -> {'station_id', 'lane', 'position', 'coords'} from wallboxes XML
ev_vehicles = set()
car_log = []
evse_log = []
charging_sessions_log = []      # log for complete charging sessions


# ----------------------------------------------------
# RAMP UP FUNCTION
# ----------------------------------------------------

def compute_setup_power(sim_time, start_time, setup_time ):
    if sim_time - (start_time+setup_time) > 0:
        return sim_time - (start_time+setup_time)
    else:
        return 0


# ----------------------------------------------------
# CHARGING STATION CACHE
# ----------------------------------------------------

def build_charging_station_cache():
    global charging_stations_cache
    charging_stations_cache = {}

    try:
        for cs_id in traci.chargingstation.getIDList():
            lane = traci.chargingstation.getLaneID(cs_id)
            start = traci.chargingstation.getStartPos(cs_id)
            end   = traci.chargingstation.getEndPos(cs_id)

            if lane not in charging_stations_cache:
                charging_stations_cache[lane] = []

            charging_stations_cache[lane].append((cs_id, start, end))

    except traci.TraCIException:
        print("WARN: No charging stations found")
    
def find_station(veh_id):
    """Lane-based cache with prefix/fallback matching."""
    try:
        lane = traci.vehicle.getLaneID(veh_id)
        if not lane:
            return None

        pos = traci.vehicle.getLanePosition(veh_id)

        # direct match
        if lane in charging_stations_cache:
            for cs_id, start, end in charging_stations_cache[lane]:
                if (start - POSITION_TOLERANCE) <= pos <= (end + POSITION_TOLERANCE):
                    return cs_id

        # prefix match (e.g. cs lane 'edge_0' matches vehicle 'edge_0_0')
        for cs_lane, entries in charging_stations_cache.items():
            if lane.startswith(cs_lane) or cs_lane.startswith(lane):
                for cs_id, start, end in entries:
                    if (start - POSITION_TOLERANCE) <= pos <= (end + POSITION_TOLERANCE):
                        return cs_id

        # fallback: check all stations regardless of lane
        for entries in charging_stations_cache.values():
            for cs_id, start, end in entries:
                if (start - POSITION_TOLERANCE) <= pos <= (end + POSITION_TOLERANCE):
                    return cs_id

    except traci.TraCIException:
        return None

    return None


def get_distance_to_position(veh_id, target_pos):
    """Calculate Euclidean distance from vehicle to target position."""
    try:
        veh_x, veh_y = traci.vehicle.getPosition(veh_id)
        target_x, target_y = target_pos
        dist = ((veh_x - target_x) ** 2 + (veh_y - target_y) ** 2) ** 0.5
        return dist
    except:
        return float('inf')


def is_vehicle_at_home(veh_id, home_position, tolerance=10.0):
    """Check if vehicle is at its home position (within tolerance)."""
    dist = get_distance_to_position(veh_id, home_position)
    return dist <= tolerance


def load_wallboxes_from_network():
    """
    Load private wallbox data from XML (NOT exposed to SUMO routing).
    Returns dict mapping: vehicle_id -> {'station_id': str, 'lane': str, 'position': float, 'coords': (x,y)}
    Wallboxes are managed purely in TraCI - stationfinder cannot route vehicles to them.
    """
    wallbox_map = {}
    wallbox_file = os.path.join(SCENARIO_DIR, "private_wallboxes.xml")
    
    if not os.path.exists(wallbox_file):
        print(f"[WARNING] No private_wallboxes.xml found at {wallbox_file}")
        return wallbox_map
    
    try:
        tree = ET.parse(wallbox_file)
        root = tree.getroot()
        
        for cs_elem in root.findall('.//chargingStation'):
            station_id = cs_elem.get('id')
            station_lane = cs_elem.get('lane')
            station_startpos = float(cs_elem.get('startPos', 0))
            station_endpos = float(cs_elem.get('endPos', 5))
            
            # Extract owner from wallbox_personXXX format
            if station_id and station_id.startswith('wallbox_'):
                owner_id = station_id.replace('wallbox_', '')
                
                # Get lane coordinates
                try:
                    lane_shape = traci.lane.getShape(station_lane)
                    if len(lane_shape) >= 2:
                        x = sum(p[0] for p in lane_shape) / len(lane_shape)
                        y = sum(p[1] for p in lane_shape) / len(lane_shape)
                    else:
                        x, y = lane_shape[0]
                    
                    wallbox_map[owner_id] = {
                        'station_id': station_id,
                        'lane': station_lane,
                        'position': (station_startpos + station_endpos) / 2,
                        'coords': (x, y)
                    }
                except Exception as e:
                    print(f"[WARNING] Failed to get coordinates for {station_id}: {e}")
                    continue
        
        print(f"[INFO] Loaded {len(wallbox_map)} private wallboxes as VIRTUAL stations (not exposed to SUMO)")
        for owner, data in list(wallbox_map.items())[:3]:
            print(f"  {owner} -> {data['station_id']} at {data['coords']}")
        if len(wallbox_map) > 3:
            print(f"  ... and {len(wallbox_map)-3} more")
    
    except Exception as e:
        print(f"[ERROR] Failed to load wallboxes: {e}")
    
    return wallbox_map


def assign_wallbox_to_owner(vid):
    """
    Assign a virtual wallbox to its owner vehicle when they first spawn.
    Called dynamically as vehicles enter the simulation.
    """
    global home_stations, vehicle_home_positions, home_charging_cache, wallbox_map
    
    try:
        # Check if this vehicle owns a wallbox
        if vid not in wallbox_map:
            return False
        
        wallbox_data = wallbox_map[vid]
        station_id = wallbox_data['station_id']
        station_x, station_y = wallbox_data['coords']
        
        # Record vehicle's current position as home
        start_x, start_y = traci.vehicle.getPosition(vid)
        vehicle_home_positions[vid] = (start_x, start_y)
        
        # Map vehicle to virtual wallbox (only accessible to owner)
        home_stations[vid] = station_id
        home_charging_cache[station_id] = (station_x, station_y, 50.0)  # 50m proximity for home charging
        
        # Create EVSE object for virtual wallbox (only accessible to owner)
        evse_objects[station_id] = EVSE_class(
            efficiency=0.95,
            Prated_kW=11.0,  # 11kW for home wallbox
            evse_id=station_id,
            energy_pool=energy_pool
        )
        
        print(f"[WALLBOX_ASSIGNED] {vid} -> {station_id} (VIRTUAL) at ({station_x:.1f}, {station_y:.1f})")
        return True
    
    except Exception as e:
        print(f"[ERROR] Failed to assign wallbox to {vid}: {e}")
        import traceback
        traceback.print_exc()
        return False


def log_charging_session_end(veh_id, station_id, end_time, energy_kwh, soc_start, soc_end,
                               v2g_energy_kwh=0.0, duration_sec=0, start_time=None):
    """
    Log a complete charging session when it ends.
    A session = entire plug-in to unplug period (not split on charge/V2G transitions).
    """
    if not TRACK_CHARGING_SESSIONS:
        return
    
    actual_duration = duration_sec
    if start_time is not None and actual_duration == 0:
        actual_duration = end_time - start_time
    
    charging_sessions_log.append({
        "veh_id": veh_id,
        "station_id": station_id,
        "end_time": end_time,
        "energy_kwh": energy_kwh,
        "v2g_energy_kwh": round(v2g_energy_kwh, 4),
        "net_energy_kwh": round(energy_kwh - v2g_energy_kwh, 4),
        "soc_start": soc_start,
        "soc_end": soc_end,
        "duration_sec": round(actual_duration, 1)
    })


# ----------------------------------------------------
# MAIN LOOP
# ----------------------------------------------------

def main():
    print("Hal")
    global energy_pool, grid_controller, peak_grid_usage_kw
    
    print("Starting SUMO with config:", SUMO_CONFIG)

    traci.start(["sumo", "-c", SUMO_CONFIG, "--start"])
    build_charging_station_cache()
    
    # Load wallbox data once at simulation start (NOT exposed to SUMO routing)
    global wallbox_map
    wallbox_map = load_wallboxes_from_network()
    
    # Load power grid if available
    power_grid_file = os.path.join(SCENARIO_DIR, "power_grid.pkl")
    if USE_GRID_CONTROLLER and os.path.exists(power_grid_file):
        try:
            print(f"[INFO] Loading power grid from {power_grid_file}")
            grid_manager = PowerGridManager.load(power_grid_file)
            grid_controller = GridController(grid_manager, max_total_power_kw=MAX_TOTAL_GRID_POWER_KW)
            energy_pool = grid_controller  # Use grid controller as energy pool
            print(f"[SUCCESS] Using GridController with {len(grid_manager.net.bus)} buses")
        except Exception as e:
            print(f"[WARNING] Failed to load grid controller: {e}")
            print("[INFO] Falling back to simple EnergyPool")
            energy_pool = EnergyPool(max_total_power_kw=MAX_TOTAL_GRID_POWER_KW)
    else:
        print("[INFO] Using simple EnergyPool (no grid model)")
        energy_pool = EnergyPool(max_total_power_kw=MAX_TOTAL_GRID_POWER_KW)

    start_time = time.time()

    step = 0
    
    # Chart data collection
    chart_power_timeline = []  # List of {time, demand_kw, usage_kw} for power timeline (requested vs actual)
    chart_v2g_timeline = []    # List of (sim_time, v2g_discharge_kw) for V2G timeline

    # Optional simulation time cap from UI parameters
    _sim_duration_cap = int(_sim_params.get('duration', 0))

    while traci.simulation.getMinExpectedNumber() > 0:
        sim_time = traci.simulation.getTime()

        # Stop if duration cap is set and reached
        if _sim_duration_cap > 0 and sim_time >= _sim_duration_cap:
            print(f"[INFO] Simulation duration cap reached ({_sim_duration_cap}s). Stopping.")
            break

        # Reset energy pool requests at the start of each step
        energy_pool.reset_requests()
        print("hallo")
        # detect EVs
        if step % 10 == 0:

            current_vehicles = set(traci.vehicle.getIDList())
            ev_vehicles.update({
                vid for vid in current_vehicles
                if is_ev_type(traci.vehicle.getTypeID(vid))
            })

        # count time
        if step % 1000 == 0:
            elapsed = time.time() - start_time
            total_demand = energy_pool.get_total_requested_power()
            total_usage = energy_pool.get_total_power_usage()
            print(f"Sim time: {sim_time:.1f}s, Elapsed real time: {elapsed:.1f}s")
            
            if grid_controller:
                grid_state = grid_controller.get_grid_state()
                print(f"  Grid: Requested={total_demand:.1f}kW, Usage={total_usage:.1f}kW, ")
                print(f"        V2G={grid_state['v2g_active_stations']} stations (-{grid_state['v2g_total_discharge_kw']:.1f}kW), ")
                print(f"        Voltage={grid_state.get('min_voltage_pu', 0):.3f}-{grid_state.get('max_voltage_pu', 0):.3f} pu")
            else:
                print(f"  Energy Pool: Requested={total_demand:.1f}kW, Usage={total_usage:.1f}kW, Limit={MAX_TOTAL_GRID_POWER_KW}kW")

        # MAIN LOOP FOR EV VEHICLES
        # Get currently active vehicles to avoid querying departed vehicles
        active_vehicles = set(traci.vehicle.getIDList())
        active_ev_vehicles = ev_vehicles & active_vehicles  # Intersection of tracked EVs and active vehicles
        
        for vid in list(active_ev_vehicles):
            # ensure these are defined - for logging and safe calls
            ramp_kw = 0.0
            allowed_kw = 0.0
            energy_kwh_this_step = 0.0
            kWh_delivered = 0.0

            try:
                # get SOC from SUMO
                soc = traci.vehicle.getParameter(vid, "device.battery.actualBatteryCapacity")
                max_soc = traci.vehicle.getParameter(vid, "device.battery.maximumBatteryCapacity")

                if not soc or not max_soc:
                    ev_vehicles.discard(vid)
                    continue

                soc_val = float(soc) / float(max_soc)

                # Create EV object on first appearance
                if vid not in ev_objects:
                    ev_objects[vid] = ElectricVehicles(
                        vehicle_type="bev",
                        arrival_time=sim_time,
                        initial_soc=soc_val,
                        batterycapacity_kwh=100,

                    )
                    print(f"[INIT] New EV: {vid}")
                    
                    # Check if this vehicle owns a wallbox and assign it dynamically
                    assign_wallbox_to_owner(vid)

                ev = ev_objects[vid]

                # Check if vehicle is at home BEFORE updating from SUMO
                # (home charging is managed by Python model, not SUMO)
                ev_is_at_home = False
                if vid in home_stations:
                    home_station_id = home_stations[vid]
                    home_pos_x, home_pos_y, home_tolerance = home_charging_cache[home_station_id]
                    veh_x, veh_y = traci.vehicle.getPosition(vid)
                    distance_to_home = ((veh_x - home_pos_x) ** 2 + (veh_y - home_pos_y) ** 2) ** 0.5
                    speed = traci.vehicle.getSpeed(vid)
                    ev_is_at_home = distance_to_home <= home_tolerance and speed < 0.2
                
                # Only update from SUMO if NOT at home (prevents overwriting home charging progress)
                if not ev_is_at_home:
                    ev.update_soc_from_sumo(float(soc), float(max_soc))
                    soc_val = ev.soc  # Use updated Python model SOC
                else:
                    # At home: use Python model's SOC (don't overwrite with SUMO's frozen value)
                    soc_val = ev.soc

                # detect charging
                speed = traci.vehicle.getSpeed(vid)
                station_id = None
                is_charging = False

                if speed < 0.2:
                    station_id = find_station(vid)
                    if station_id:
                        is_charging = True

                # update charging status
                prev_status = charging_status.get(vid, (False, None))
                was_charging = prev_status[0]
                prev_station = prev_status[1]

                charging_status[vid] = (is_charging, station_id)

                # EVSE management
                if is_charging and station_id:
                    # construct EVSE object if not exists (for public charging stations)
                    if station_id not in evse_objects:
                        evse_objects[station_id] = EVSE_class(
                            efficiency=0.95,
                            Prated_kW=MAX_CHARGING_POWER_KW,
                            evse_id=station_id,
                            energy_pool=energy_pool  # Pass global energy pool
                        )

                    evse = evse_objects[station_id]
                    print("hi")

                    # RAMP UP handling
                    if vid not in charging_start_time:
                        charging_start_time[vid] = sim_time
                        charging_session_energy[vid] = 0.0
                        session_start_soc[vid] = soc_val  # Save starting SOC (separate dict, not overwritten)
                        print("[CHARGING_STARTED]")

                    if evse.charging_process is None:


                        evse.set_ChargingProcess(
                            charging_process=CHProcess(charging_start_time[vid]+ev.modelparameters['ev_setuptime'],
                                                       one_phase=False, Pmax = evse.getPrated_kw(),
                                                       efficiency=evse.getEfficiency(), with_departure=False,
                                                departure_time=None, ev_soc=ev.soc, crate=ev.modelparameters['ev_crate'],
                                                             packcap=ev.modelparameters['ev_packcapacity']))



                    ramp_kw = evse.compute_power(sim_time)
                    print(ramp_kw)
                    print(sim_time)
                     # HIer folgendes: EVSE/EnergyPool berechnet ramp-up-phase (einmalig am Anfang) und dann stagnant (zuordnung zu vid)
                    # resultierte Leistung wird von energy pool zeitabhängig zurückgegeben und falls deutlich weniger (Runterregelung) stagnante werte noch skaliert
                    #Energy Pool bleibt wie er ist. Wenn reQuest gestellt wird, wird  der verfügbare Strom berechnet es wird die sim-time und die Star time abzüglich der Setup time übergeben.
                    # Für eine Kombination aus einem  ev und dem Energy Pool gibt es eine zusätzliche Instanz die bei ersten request von dem Ev ein Ramp-up berechnet.
                    # Bei zukünftigen requests wird immer geschaut ob die Ramp-up time schon vorbei ist und je nachdem der Strom berechnet. Energy Pool wird immer entsprechend dieses Stromes aktualisiert.
                    # Falls wir nach der Rampe time sind, wird die stagnante Phase berechnet und auch wieder der Strom beim energy Pool entsprechend aktualisiert und an das IV gesendet.
                    # Falls nun Regelungen beim Strom passieren nach unten oder nach oben vom energy Pool dann wird die stagnante Phase entsprechend skaliert und die Werte entsprechend aktualisiert an das EV gesend.
                    # Ramp down passiert über die Batterie Modellierung.
                    # Parameter: Stagnant kann optional auch einfach kosntant bleiben.
                    # KlassenInstanzen als dict-Atribut in nergy-Pool (mit stationIDs), jeder Eintrag ist Klasseninstanz.


                    # Frage: wei merken  EVSE/EnergyPool dass ramp-up phase schon berechnet wurde? bzw. wann wird ramp_up-phase gelöscht
                        #--> einfach, wenn ramp-up phase vorbei ist, wird die zugehörige Instanz gelöscht.
                        #--> bei stagnant?
                        #wir brauchen reset von ramp_up und stagnant, wenn was_charging-Schleife erreicht wird
                        # nachdem geladen wurde --> über station_id/is_charging/was charging (was_charging sagt ob vorher geladen wurd und is_charging ob aktuell)
                        # im was_charging-Block EVSE/ EnergyPool informieren für reset
                    # am besten über EVSE, da hier shcon Zuordnung zu auto und es geht ja auch um PredictiveMaintenance der Ladesäulen!


                    # Register this station's request with the energy pool
                    energy_pool.register_station_request(station_id, ramp_kw)

                    # inform EVSE from server (server_setpoint will be ramped)
                    evse.receive_from_server(ramp_kw)

                    # inform EVSE from EV
                    evse.receive_from_ev(
                        Vbatt=ev.packvoltage,
                        Pbatt_kW=ev.packpower / 1000,
                        soc=ev.soc,
                        plugged=True,
                        ready=ev.readytocharge
                    )

                    # EVSE gives allowed power (kW)
                    allowed_kw = evse.send_to_ev()

                    # Update energy pool with actual usage
                    energy_pool.update_station_power_usage(station_id, allowed_kw)

                    # charge EV in Python model with allowed power
                    # dt=10 matches SUMO step-length of 10 seconds
                    ev.chargevehicle(simulationtime=sim_time, dt=SUMO_STEP_LENGTH, kw=allowed_kw)

                    # set SUMO charging power (W)
                    w = allowed_kw * 1000
                    traci.chargingstation.setChargingPower(station_id, w)

                    # Accumulate energy during this session (kWh per step, step = 10 seconds)
                    energy_kwh_this_step = allowed_kw * SUMO_STEP_LENGTH / 3600.0
                    charging_session_energy[vid] = charging_session_energy.get(vid, 0.0) + energy_kwh_this_step

                    # Re-read updated SOC after charging
                    soc_val = ev.soc

                    # Debug print when value changes notably
                    prev = evse_log[-1]["allowed_kw"] if evse_log else None
                    if prev is None or abs(allowed_kw - prev) > 0.1:
                        total_requested = energy_pool.get_total_requested_power()
                        #if total_requested > MAX_TOTAL_GRID_POWER_KW:
                        #    print(f"[EVSE] time={sim_time} veh={vid} station={station_id} ramp_kw={ramp_kw:.2f} allowed_kw={allowed_kw:.2f} (limited by pool: {total_requested:.1f}kW > {MAX_TOTAL_GRID_POWER_KW}kW)")
                        #else:
                        #    print(f"[EVSE] time={sim_time} veh={vid} station={station_id} ramp_kw={ramp_kw:.2f} allowed_kw={allowed_kw:.2f}")

                    # periodically flush evse_log to disk
                    if EVSE_LOG_FLUSH_INTERVAL and (step % EVSE_LOG_FLUSH_INTERVAL == 0):
                        pd.DataFrame(car_log).to_csv(OUTPUT_CHARGING_LOG, index=False)
                        print(f"EVSE log flushed ${len(car_log)} entries to disk.")
                        car_log.clear()

                else:
                    # Charging session ended
                    if was_charging and vid in charging_start_time:
                        evse = evse_objects[prev_station] # todo: check, funktioniert das immer?
                        evse.reset_ChargingProcess()  # Reset EVSE state for next session
                        soc_start = session_start_soc.get(vid, last_soc.get(vid, 0.0))
                        soc_end = soc_val
                        total_energy = charging_session_energy.get(vid, 0.0)
                        kWh_delivered = total_energy

                        log_charging_session_end(vid, prev_station, sim_time, total_energy, soc_start, soc_end)
                        
                        if total_energy > 0.01:
                            print(f"[SESSION] veh={vid} station={prev_station} energy={total_energy:.3f} kWh soc:{soc_start:.2f}->{soc_end:.2f}")
                        
                        # Only clear tracking when actually ending a public charging session
                        charging_start_time.pop(vid, None)
                        charging_session_energy.pop(vid, None)
                        session_start_soc.pop(vid, None)


                # ========== HOME CHARGING LOGIC FOR DESIGNATED HOME STATIONS ==========
                # Session = entire plug-in to unplug period (NOT split when switching charge <-> V2G)
                if vid in home_stations:
                    home_station_id = home_stations[vid]
                    home_evse = evse_objects[home_station_id]
                    if ev_is_at_home:
                        # Start home session tracker if not already started
                        if vid not in home_session_tracker:
                            home_session_tracker[vid] = {
                                'start_time': sim_time,
                                'start_soc': soc_val,
                                'charge_kwh': 0.0,
                                'v2g_kwh': 0.0,
                                'station_id': home_station_id
                            }
                            home_pos_x, home_pos_y, _ = home_charging_cache[home_station_id]

                        if home_evse.charging_process is None:

                            home_evse.set_ChargingProcess(
                                charging_process=CHProcess(
                                    sim_time + ev.modelparameters['ev_setuptime'],
                                    one_phase=False, Pmax=home_evse.getPrated_kw(),
                                    efficiency=home_evse.getEfficiency(), with_departure=False,
                                    departure_time=None, ev_soc=ev.soc, crate=ev.modelparameters['ev_crate'],
                                    packcap=ev.modelparameters['ev_packcapacity']))
                            print("[CHARGING_STARTED]")
                            print(f"[HOME_SESSION_START] veh={vid} at ({home_pos_x:.1f}, {home_pos_y:.1f}) soc={soc_val:.2f}")

                        grid_usage_percent = (energy_pool.get_total_requested_power() / MAX_TOTAL_GRID_POWER_KW) * 100

                        
                        # Check if V2G should be activated (high SOC + grid needs support)
                        should_v2g = soc_val >= V2G_SOC_THRESHOLD and grid_usage_percent >= GRID_CAPACITY_WARNING_THRESHOLD * 100
                        
                        if should_v2g:
                            # Switch to V2G mode — session continues (no session end!)
                            # Reset ramp timer (will restart when switching back to charging)
                            charging_start_time.pop(vid, None)
                            home_evse.reset_ChargingProcess()

                            home_evse.set_discharge_mode(True)
                            
                            # Calculate discharge power (limited by max discharge rate and remaining energy)
                            remaining_energy_kwh = soc_val * float(max_soc) / 1000.0
                            max_safe_discharge_kw = remaining_energy_kwh * 0.2  # 0.2C rate
                            v2g_discharge_kw = min(V2G_DISCHARGE_POWER_KW, max_safe_discharge_kw)
                            
                            # Register V2G with grid controller
                            if grid_controller:
                                grid_controller.register_v2g_discharge(home_station_id, v2g_discharge_kw)
                            
                            # Inform EVSE for V2G discharge
                            home_evse.receive_from_server(-v2g_discharge_kw)
                            home_evse.receive_from_ev(
                                Vbatt=ev.packvoltage,
                                Pbatt_kW=ev.packpower / 1000,
                                soc=ev.soc,
                                plugged=True,
                                ready=True
                            )
                            
                            v2g_power_allowed = home_evse.send_to_ev()
                            if v2g_power_allowed < 0:
                                energy_removed_wh = ev.dischargevehicle(simulationtime=sim_time, dt=10, kw=abs(v2g_power_allowed))
                                v2g_energy_step = energy_removed_wh / 3600.0
                                v2g_session_energy[vid] = v2g_session_energy.get(vid, 0.0) + v2g_energy_step
                                home_session_tracker[vid]['v2g_kwh'] += v2g_energy_step
                                
                                energy_pool.update_station_power_usage(home_station_id, v2g_power_allowed)
                                
                                if step % 100 == 0 and energy_removed_wh > 0:
                                    print(f"[V2G] veh={vid} at_home={distance_to_home:.1f}m discharge={abs(v2g_power_allowed):.1f}kW soc={soc_val:.2f} grid={grid_usage_percent:.1f}%")
                        
                        elif soc_val < 0.95:  # Normal charging at home
                            print("WTF")
                            home_evse.set_discharge_mode(False)
                            
                            if vid not in charging_start_time:
                                charging_start_time[vid] = sim_time
                                charging_session_energy[vid] = 0.0
                                session_start_soc[vid] = soc_val  # Save starting SOC (separate dict, not overwritten)

                            if home_evse.charging_process is None:

                                home_evse.set_ChargingProcess(
                                    charging_process=CHProcess(
                                        charging_start_time[vid] + ev.modelparameters['ev_setuptime'],
                                        one_phase=False, Pmax=home_evse.getPrated_kw(),
                                        efficiency=home_evse.getEfficiency(), with_departure=False,
                                        departure_time=None, ev_soc=ev.soc, crate=ev.modelparameters['ev_crate'],
                                        packcap=ev.modelparameters['ev_packcapacity']))
                                print("[CHARGING_STARTED]")
                                home_pos_x, home_pos_y, _ = home_charging_cache[home_station_id]
                                print(f"[HOME_CHARGE_START] veh={vid} at home position ({home_pos_x:.1f}, {home_pos_y:.1f})")

                            home_ramp_kw = home_evse.compute_power(sim_time)
                            print(ramp_kw)
                            print(sim_time)
                            energy_pool.register_station_request(home_station_id, home_ramp_kw)
                            
                            home_evse.receive_from_server(home_ramp_kw)
                            home_evse.receive_from_ev(
                                Vbatt=ev.packvoltage,
                                Pbatt_kW=ev.packpower / 1000,
                                soc=ev.soc,
                                plugged=True,
                                ready=ev.readytocharge
                            )
                            
                            home_charge_kw = home_evse.send_to_ev()
                            if home_charge_kw > 0:
                                ev.chargevehicle(simulationtime=sim_time, dt=10, kw=home_charge_kw)
                                energy_pool.update_station_power_usage(home_station_id, home_charge_kw)
                                energy_kwh_this_step = home_charge_kw * SUMO_STEP_LENGTH / 3600.0
                                home_session_tracker[vid]['charge_kwh'] += energy_kwh_this_step
                                
                                soc_val = ev.soc
                                
                                if step % 100 == 0:
                                    print(f"[HOME_CHARGE] veh={vid} at_home={distance_to_home:.1f}m ramp={home_ramp_kw:.2f}kW power={home_charge_kw:.2f}kW soc={soc_val:.2f}")
                        
                        else:
                            print("WTF2")
                            # SOC >= 0.95 and no V2G needed — idle at home (still plugged in, session continues)
                            charging_start_time.pop(vid, None)  # Stop ramp timer
                            home_evse.reset_ChargingProcess()
                    
                    else:
                        # Vehicle left home — end the entire home session
                        if vid in home_session_tracker:

                            home_evse.reset_ChargingProcess()
                            session = home_session_tracker.pop(vid)
                            soc_end = ev.soc
                            log_charging_session_end(
                                vid, session['station_id'], sim_time,
                                session['charge_kwh'], session['start_soc'], soc_end,
                                v2g_energy_kwh=session['v2g_kwh'],
                                start_time=session['start_time']
                            )
                            duration = sim_time - session['start_time']
                            print(f"[HOME_SESSION_END] veh={vid} station={session['station_id']} "
                                  f"charged={session['charge_kwh']:.3f}kWh v2g={session['v2g_kwh']:.3f}kWh "
                                  f"soc:{session['start_soc']:.2f}->{soc_end:.2f} duration={duration:.0f}s (left home)")
                        
                        charging_start_time.pop(vid, None)
                        home_evse.reset_ChargingProcess()

                x, y = traci.vehicle.getPosition(vid)
                car_log.append({
                    "time": sim_time,
                    "veh_id": vid,
                    "speed": speed,
                    "x": x,
                    "y": y,
                    "station": station_id,
                    "allowed_kw": allowed_kw,
                    "ramp_kw": ramp_kw,
                    "energy": kWh_delivered,
                    "soc": ev.soc,
                    "edge_id": traci.vehicle.getRoadID(vid),
                    "is_charging": is_charging
                })

                last_soc[vid] = soc_val

            except traci.TraCIException:
                ev_vehicles.discard(vid)
        
        # Finalize power allocation for this step (enforces grid constraints)
        # Results are used by get_available_power_for_station() in the next step
        energy_pool.finalize_step()
        
        # Collect chart data: power timeline and V2G timeline
        total_demand = energy_pool.get_total_requested_power()
        total_usage = energy_pool.get_total_power_usage()
        chart_power_timeline.append({
            'time': sim_time, 
            'demand_kw': round(total_demand, 1),
            'usage_kw': round(total_usage, 1)
        })
        
        # V2G supply (negative values in requests become positive discharge)
        v2g_discharge = 0
        if hasattr(energy_pool, 'v2g_stations'):
            v2g_discharge = abs(sum(energy_pool.v2g_stations.values()))
        chart_v2g_timeline.append({'time': sim_time, 'v2g_kw': round(v2g_discharge, 1)})
        
        # Track peak grid usage (based on actual delivered power after throttling)
        step_usage = energy_pool.get_total_power_usage()
        if step_usage > peak_grid_usage_kw:
            peak_grid_usage_kw = step_usage
        
        traci.simulationStep()
        sim_time = traci.simulation.getTime()  # update sim_time after step
        step += 1

    # ----------------------------------------------------
    # FINISH
    # ----------------------------------------------------

    traci.close()

    runtime = time.time() - start_time
    print("Simulation finished. Runtime:", runtime)

    # Flush any home sessions still active at sim end
    for vid, session in list(home_session_tracker.items()):
        soc_end = ev_objects[vid].soc if vid in ev_objects else session['start_soc']
        log_charging_session_end(
            vid, session['station_id'], sim_time,
            session['charge_kwh'], session['start_soc'], soc_end,
            v2g_energy_kwh=session['v2g_kwh'],
            start_time=session['start_time']
        )
        duration = sim_time - session['start_time']
        print(f"[HOME_SESSION_END] veh={vid} station={session['station_id']} "
              f"charged={session['charge_kwh']:.3f}kWh v2g={session['v2g_kwh']:.3f}kWh "
              f"soc:{session['start_soc']:.2f}->{soc_end:.2f} duration={duration:.0f}s (sim ended)")
    home_session_tracker.clear()

    pd.DataFrame(car_log).to_csv(OUTPUT_CHARGING_LOG, index=False)
    
    if charging_sessions_log:
        sessions_file = os.path.join(LOGS_DIR, "charging_sessions.csv")
        pd.DataFrame(charging_sessions_log).to_csv(sessions_file, index=False)
        print(f"[LOG] Charging sessions written: {sessions_file}")

    # ----------------------------------------------------
    # GENERATE SIMPLE GRID POWER CHART FOR UI
    # ========================================
    import json as _json
    
    # Resample power timeline to 2-minute buckets
    bucket_size = 12  # 12 * 10-second steps = 2 minutes
    timeline_buckets = {}
    for dp in chart_power_timeline:
        bucket = int(dp['time'] / (bucket_size * 10)) * (bucket_size * 10)
        if bucket not in timeline_buckets:
            timeline_buckets[bucket] = {'demand': [], 'usage': []}
        timeline_buckets[bucket]['demand'].append(dp['demand_kw'])
        timeline_buckets[bucket]['usage'].append(dp['usage_kw'])
    
    timeline_times = sorted(timeline_buckets.keys())
    timeline_demands = [sum(timeline_buckets[t]['demand']) / len(timeline_buckets[t]['demand']) for t in timeline_times]
    timeline_usage = [sum(timeline_buckets[t]['usage']) / len(timeline_buckets[t]['usage']) for t in timeline_times]
    
    # Time labels
    time_labels = []
    for t in timeline_times:
        mins = int(t // 60)
        hours = mins // 60
        mins = mins % 60
        time_labels.append(f"{hours}:{mins:02d}")
    
    # Grid Power Chart (the working one)
    charts_data = {
        "type": "line",
        "labels": time_labels,
        "datasets": [
            {
                "label": "Total Demand (kW)",
                "data": [round(d, 1) for d in timeline_demands],
                "borderColor": "rgb(75, 145, 255)",
                "backgroundColor": "rgba(75, 145, 255, 0.1)",
                "borderWidth": 2,
                "fill": True,
                "tension": 0.3
            },
            {
                "label": "Actual Usage (kW)",
                "data": [round(u, 1) for u in timeline_usage],
                "borderColor": "rgb(54, 162, 235)",
                "backgroundColor": "rgba(54, 162, 235, 0.2)",
                "borderWidth": 2,
                "fill": True,
                "tension": 0.3
            },
            {
                "label": f"Grid Limit ({MAX_TOTAL_GRID_POWER_KW} kW)",
                "data": [MAX_TOTAL_GRID_POWER_KW] * len(time_labels),
                "borderColor": "rgb(255, 99, 99)",
                "borderDash": [5, 5],
                "borderWidth": 2,
                "fill": False,
                "pointRadius": 0
            }
        ]
    }
    
    charts_file = os.path.join(LOGS_DIR, "charts_data.json")
    with open(charts_file, 'w', encoding='utf-8') as f:
        _json.dump(charts_data, f, indent=2)
    print(f"[LOG] Grid power chart written: {charts_file}")

    # ----------------------------------------
    # V2G / CHARGING SUMMARY STATISTICS
    # ----------------------------------------------------
    import json as _json

    # Categorise charging sessions
    public_sessions = []
    wallbox_sessions = []
    for s in charging_sessions_log:
        sid = s.get('station_id', '')
        if sid.startswith('wallbox_'):
            wallbox_sessions.append(s)
        else:
            public_sessions.append(s)

    # ----------------------------------------
    # PER-STATION STATISTICS
    # ----------------------------------------
    from collections import defaultdict
    
    station_stats = defaultdict(lambda: {
        'station_id': '',
        'charging_sessions': 0,
        'unique_vehicles': set(),
        'total_energy_charged_kwh': 0.0,
        'total_energy_discharged_kwh': 0.0,
        'net_energy_kwh': 0.0,
        'max_power_demanded_kw': 0.0,
        'is_wallbox': False
    })
    
    # Process all charging sessions to build per-station stats
    for session in charging_sessions_log:
        sid = session.get('station_id', '')
        if not sid:
            continue
            
        station_stats[sid]['station_id'] = sid
        station_stats[sid]['charging_sessions'] += 1
        station_stats[sid]['unique_vehicles'].add(session.get('veh_id', ''))
        station_stats[sid]['total_energy_charged_kwh'] += session.get('energy_kwh', 0.0)
        station_stats[sid]['total_energy_discharged_kwh'] += session.get('v2g_energy_kwh', 0.0)
        station_stats[sid]['net_energy_kwh'] += session.get('net_energy_kwh', 0.0)
        station_stats[sid]['is_wallbox'] = sid.startswith('wallbox_')
        
    # Load charging station power info from XML files
    station_power_map = {}  # station_id -> power_kw
    
    # Read from combined_additional.xml or individual charging station files
    additional_files = [
        os.path.join(SCENARIO_DIR, "combined_additional.xml"),
        os.path.join(SCENARIO_DIR, "osm.chargingstations.xml"),
        os.path.join(SCENARIO_DIR, "private_wallboxes.xml")
    ]
    
    for xml_file in additional_files:
        if os.path.exists(xml_file):
            try:
                tree = ET.parse(xml_file)
                root = tree.getroot()
                for cs in root.findall('.//chargingStation'):
                    cs_id = cs.get('id')
                    power_w = float(cs.get('power', 0))
                    if cs_id and power_w > 0:
                        station_power_map[cs_id] = power_w / 1000.0  # Convert to kW
            except Exception:
                pass
    
    # Track max power from evse_objects (for dynamic stations)
    for sid, evse in evse_objects.items():
        max_power_w = getattr(evse, 'chargingpower', 0)
        if max_power_w > 0:
            station_power_map[sid] = max_power_w / 1000.0
    
    # Apply power info to all station stats
    for sid in station_stats:
        if sid in station_power_map:
            station_stats[sid]['max_power_demanded_kw'] = station_power_map[sid]
        elif sid.startswith('real_cs_'):
            # Default for real charging stations if not found
            station_stats[sid]['max_power_demanded_kw'] = 50.0
        elif sid.startswith('wallbox_'):
            # Default for wallboxes
            station_stats[sid]['max_power_demanded_kw'] = 11.0
    
    # Convert sets to counts for JSON serialization
    station_stats_serializable = {}
    for sid, stats in station_stats.items():
        station_stats_serializable[sid] = {
            'station_id': stats['station_id'],
            'charging_sessions': stats['charging_sessions'],
            'unique_vehicles': len(stats['unique_vehicles']),
            'total_energy_charged_kwh': round(stats['total_energy_charged_kwh'], 2),
            'total_energy_discharged_kwh': round(stats['total_energy_discharged_kwh'], 2),
            'net_energy_kwh': round(stats['net_energy_kwh'], 2),
            'max_power_kw': round(stats['max_power_demanded_kw'], 1),
            'is_wallbox': stats['is_wallbox']
        }
    
    # Save per-station statistics
    station_stats_file = os.path.join(LOGS_DIR, "station_statistics.json")
    with open(station_stats_file, 'w', encoding='utf-8') as f:
        _json.dump(station_stats_serializable, f, indent=2)
    print(f"[LOG] Per-station statistics written: {station_stats_file}")

    total_public_energy = sum(s.get('energy_kwh', 0) for s in public_sessions)
    total_wallbox_charge_energy = sum(s.get('energy_kwh', 0) for s in wallbox_sessions)
    total_wallbox_v2g_energy = sum(s.get('v2g_energy_kwh', 0) for s in wallbox_sessions)
    total_v2g_energy = sum(v for v in v2g_session_energy.values())

    # Count unique vehicles per category
    public_vehicles = set(s['veh_id'] for s in public_sessions)
    wallbox_vehicles = set(s['veh_id'] for s in wallbox_sessions)
    v2g_vehicles = set(v for v, e in v2g_session_energy.items() if e > 0)

    # Home charging info
    home_charge_vehicles = set(home_stations.keys())

    v2g_summary = {
        "runtime_seconds": round(runtime, 1),
        "sim_duration_seconds": sim_time,
        "total_evs": len(ev_objects),
        "total_wallboxes": len(wallbox_map),
        "total_public_stations": len([s for s in evse_objects if not s.startswith('wallbox_')]),
        "charging": {
            "public": {
                "sessions": len(public_sessions),
                "unique_vehicles": len(public_vehicles),
                "total_energy_kwh": round(total_public_energy, 2)
            },
            "wallbox": {
                "sessions": len(wallbox_sessions),
                "unique_vehicles": len(wallbox_vehicles),
                "total_energy_kwh": round(total_wallbox_charge_energy, 2),
                "total_v2g_energy_kwh": round(total_wallbox_v2g_energy, 2),
                "net_energy_kwh": round(total_wallbox_charge_energy - total_wallbox_v2g_energy, 2),
                "wallbox_count": len(wallbox_map)
            }
        },
        "v2g": {
            "active_vehicles": len(v2g_vehicles),
            "total_discharged_kwh": round(total_v2g_energy, 2),
            "vehicles": {vid: round(e, 3) for vid, e in v2g_session_energy.items() if e > 0}
        },
        "grid": {
            "max_power_kw": MAX_TOTAL_GRID_POWER_KW,
            "peak_usage_kw": round(peak_grid_usage_kw, 1)
        }
    }

    v2g_stats_file = os.path.join(LOGS_DIR, "v2g_summary.json")
    with open(v2g_stats_file, 'w', encoding='utf-8') as f:
        _json.dump(v2g_summary, f, indent=2)
    print(f"[LOG] V2G summary written: {v2g_stats_file}")

    print(f"[LOG] Logs for modelling written: {OUTPUT_CHARGING_LOG}")
    print(f"[LOG] TraCI simulation logs available in: {LOGS_DIR}")


if __name__ == "__main__":
    main()